### ISSUE TITLE
Default webcast window should be bigger

### ISSUE THREAD

**Issue by yami280** [ets-berkeley-edu/calcentral#3658]
It'd be nice if the webcast video player was bigger by default. Currently, you can only view it in a tiny window, full screen it, or open it in a different window.

**Comment by christianv** [comment]
Hey @yami280, thank you for providing this feedback, we'll definitely get back to you when we find a solution to fix this.

We've created an internal ticket [CLC-5207](https://jira.ets.berkeley.edu/jira/browse/CLC-5207) to track this feedback.
