### ISSUE TITLE
Hide whitespace due to empty cc-widget-profile-message

### ISSUE THREAD

**Issue by mc10** [ets-berkeley-edu/calcentral#3888]
`cc-widget-profile-message` has a `padding: 15px 15px 0px` rule attached to it, so when `cc-widget-profile-message` is empty but `showProfileMessage` is true, there is an awkward empty space between the "Profile" title and the "Academic status as of..." message. This space should be removed.

**Comment by paulkerschen** [comment]
@mc10 Resolved issue #3882 actually duplicates this, though it's not at all obvious from the description.
