### ISSUE TITLE
bcal.berkeley.edu link down

### ISSUE THREAD

**Issue by marwahaha** [ets-berkeley-edu/calcentral#4773]
Hi, I'm not sure who I should talk to about this, but the redirect link for bcal.berkeley.edu doesn't work anymore. Do you know how to get this fixed?

Best,
Kunal

**Comment by davidlimcheng** [comment]
Hi Kunal,

The redirect link was temporarily out of service, but should be good to go now.  If you continue to have problems, try clearing your browser cache/history - that should usually resolve it.  

Feel free to contact [bConnected support] (https://bconnected.berkeley.edu/collaboration-services/google/bcal) if you continue to experience any issues.

Thanks!
