### ISSUE TITLE
Enrollment rules link broken

### ISSUE THREAD

**Issue by mc10** [ets-berkeley-edu/calcentral#5110]
The "Enrollment rules" link under "Decide" in "Class Enrollment" that links to http://registrar.berkeley.edu/Records/tbinfo.html is broken.

**Comment by christianvuerings** [comment]
@mc10 Thanks for reaching out to us and letting us know about this issue. We've contacted the registrar's office and will try to get a fix in soon.

Internal ticket is at https://jira.berkeley.edu/browse/SISRP-16829

**Comment by christianvuerings** [comment]
@mc10 Thanks again for reporting this issue. The previous link should now redirect you to http://registrar.berkeley.edu/how-to-enroll-in-classes so this issue should have been fixed.
