### ISSUE TITLE
Please let faculty members hide their grades :(

### ISSUE THREAD

**Issue by cycomachead** [ets-berkeley-edu/calcentral#7634]
Is there a proper place for feature requests? I'm happy to submit one there...

Can we please fixup the "My Academics" tab for Faculty? As far as I know this is the place where faculty are actually supposed to go for some materials -- I certainly find it one of the easier places to find things. 

The teaching box works well for students who are actively teaching, but it being below my grades isn't super helpful. Never mind that because I went to Berkeley, I hate my grades and would prefer to never see them again...

There's lots of scrolling because of the transcript and degree progress blocks. A simple solution to is to order the middle column Teaching / Finals / Transcript Degree when the user has a faculty flag. However, at least in my view the right column only displays transfer credits, so there's room to balance out the masonry layout because the middle column is much longer. In that case I'd stick Teaching in the top middle, and Finals in the top right. 

Not sure I'll have the time soon, but would you accept a pull request? I really might try to make time for this...

**Comment by raydavis** [comment]
Hi, @cycomachead ! That all makes sense to me, but I'm afraid you may be knocking at the wrong door. Despite this GitHub repository being named "calcentral", the actual CalCentral site and software you're familiar is being handled by a different organization whose code was forked off from this repository some time ago. Meanwhile, we here continue to use our own version of the code for other purposes. Someone should be able to offer more assistance at the official [CalCentral Support page|https://sis.berkeley.edu/help/calcentral-support]. 

I admit this is a confusing situation, but "It seems history is to blame." I'll try to clarify the muddle at least slightly in this repository's README.

**Comment by cycomachead** [comment]
Thank you! 😄 I assume that code is not open source then? 

This very much explains why I couldn't figure out where that page was being rendered!

**Comment by raydavis** [comment]
@cycomachead , I just deleted all that unused-by-us "My Academics" rendering code from our master branch a week or two ago. :)

The SIS fork looks readable at https://github.com/sis-berkeley-edu , but I believe they track requests and bug reports through the support link.

And thank you for your patience with the ambiguous naming. We still get confused by it ourselves sometimes.
